In [76]:
import json
import math
import pandas as pd
from pathlib import Path
import re
import statistics
from tqdm import tqdm

from modules import plotting

In [77]:
wd = Path(".brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding")
grids = wd.glob("gridsearch_*/")

slurmoutToExp = {}
for grid in tqdm(grids):
    slurmoutToExp[grid.name] = {}
    experiments = list(grid.glob("wgEncode*/"))
    for slurmerrf in (grid / "slurmout").glob("*.err"):
        exp = None
        with open(slurmerrf, "r") as f:
            for line in f:
                m = re.search(r"wgEncode.+\.narrowPeak", line)
                if m:
                    exp = m.group(0)
                    break

        assert exp is not None, f"Could not find experiment name in {slurmerrf}"
        slurmoutToExp[grid.name][exp] = slurmerrf

print(slurmoutToExp)

33it [00:37,  1.14s/it]

{'gridsearch_00008': {'wgEncodeAwgTfbsHaibK562Egr1V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_11_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Atf3UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_0_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Rfx5IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_28_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Gata2UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_17_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Nr2f2sc271940V0422111UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_26_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Usf2IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_33_gridsearch_00008.err'), 'wgEncodeAwgTfbsBroadK562CtcfUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_5_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_31_gridsearch_00008.err'), 'wgEncodeAwgTfbsUwK562CtcfUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_6_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562E2f4UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_8_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Ets1V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_14_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562MaxV0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_23_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Gata2sc267Pcr1xUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_15_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562CebpbIggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_4_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Sp1Pcr1xUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_29_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Yy1V0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_37_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Gata1UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_16_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562MaxIggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_22_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Mef2aV0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_24_gridsearch_00008.err'), 'wgEncodeAwgTfbsUtaK562CtcfUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_7_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562MaffIggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_21_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Irf1Ifng30UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_19_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Usf1V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_34_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Irf1Ifna30UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_20_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Nrf1IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_27_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Nfe2UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_25_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562E2f6V0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_10_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Yy1UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_36_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_32_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Atf3V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_1_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Irf1Ifna6hUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_18_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Yy1V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_35_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_38_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Sp2sc643V0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_30_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_39_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562E2f6UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_9_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Atf106325UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_2_gridsearch_00008.err'), 'wgEncodeAwgTfbsHaibK562Elf1sc631V0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_12_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Bhlhe40nb100IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_3_gridsearch_00008.err'), 'wgEncodeAwgTfbsSydhK562Elk112771IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/slurmout/5566978_13_gridsearch_00008.err')}, 'gridsearch_00001': {'wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_39_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562E2f6V0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_10_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Rfx5IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_28_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562E2f6UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_9_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Irf1Ifng30UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_19_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Atf3UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_0_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562MaffIggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_21_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Nr2f2sc271940V0422111UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_26_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Sp1Pcr1xUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_29_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Irf1Ifna6hUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_18_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Nfe2UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_25_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Yy1V0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_37_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Gata2sc267Pcr1xUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_15_gridsearch_00001.err'), 'wgEncodeAwgTfbsUwK562CtcfUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_6_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Gata1UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_16_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Elf1sc631V0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_12_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Usf1V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_34_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562E2f4UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_8_gridsearch_00001.err'), 'wgEncodeAwgTfbsUtaK562CtcfUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_7_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Atf3V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_1_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Yy1UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_36_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Bhlhe40nb100IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_3_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562CebpbIggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_4_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Yy1V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_35_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Mef2aV0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_24_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562MaxV0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_23_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Gata2UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_17_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Atf106325UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_2_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_32_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Egr1V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_11_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Irf1Ifna30UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_20_gridsearch_00001.err'), 'wgEncodeAwgTfbsBroadK562CtcfUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_5_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Ets1V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_14_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_38_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Usf2IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_33_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Elk112771IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_13_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_31_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562Nrf1IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_27_gridsearch_00001.err'), 'wgEncodeAwgTfbsHaibK562Sp2sc643V0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_30_gridsearch_00001.err'), 'wgEncodeAwgTfbsSydhK562MaxIggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/slurmout/5566957_22_gridsearch_00001.err')}, 'gridsearch_00004': {'wgEncodeAwgTfbsSydhK562Irf1Ifng30UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_19_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562Mef2aV0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_24_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562Irf1Ifna30UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_20_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562E2f6UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_9_gridsearch_00004.err'), 'wgEncodeAwgTfbsUtaK562CtcfUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_7_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562Egr1V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_11_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562Atf3V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_1_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562Nrf1IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_27_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562Gata1UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_16_gridsearch_00004.err'), 'wgEncodeAwgTfbsUwK562CtcfUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_6_gridsearch_00004.err'), 'wgEncodeAwgTfbsBroadK562CtcfUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_5_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562Elk112771IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_13_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562Sp2sc643V0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_30_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562Nfe2UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_25_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562Atf106325UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_2_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562Bhlhe40nb100IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_3_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562MaxIggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_22_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562MaxV0416102UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_23_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562MaffIggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_21_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562Yy1V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_35_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562Yy1UcdUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_36_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_38_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562Gata2sc267Pcr1xUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_15_gridsearch_00004.err'), 'wgEncodeAwgTfbsSydhK562Rfx5IggrabUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_28_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_31_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562Nr2f2sc271940V0422111UniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_26_gridsearch_00004.err'), 'wgEncodeAwgTfbsHaibK562Sp1Pcr1xUniPk.narrowPeak': PosixPath('.brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/slurmout/5566960_2

In [78]:
# wd = Path(".brain_mnt/runs/20250425_gridsearch_STREME_vs_ProfileFinding_pinky")
# grids = wd.glob("gridsearch_*/")
ngrids = len(list(grids))
runs = []
for grid in tqdm(sorted(list(wd.glob("gridsearch_*/")))):
    # print(f"Processing {grid.name}: {list(grid.glob('wgEncode*/'))}")
    nlogs = len(list((grid / "slurmout").glob("*"))) / 2
    experiments = list(grid.glob("wgEncode*/"))
    # print(f"Experiments: {experiments}")
    nexp = len(experiments)
    if nexp != nlogs:
        print(f"Warning: {grid.name} has {nexp} experiments but {nlogs}*2 logs")
    success = []
    failed = []
    ooms = []
    for exp in experiments:
        # print(f"Processing {exp.name}")
        if (exp / "tomtom" / "tomtom.tsv").exists():
            success.append(exp)
        else:
            failed.append(exp)
            # slurmerrf = slurmoutToExp[grid.name][exp.name]
            slurmerrf = slurmoutToExp[grid.name].get(exp.name, None)
            if slurmerrf is None:
                print(f"Warning: {grid.name} has no slurmout for {exp.name}")
                continue
            with open(slurmerrf, "r") as f:
                for line in f:
                    m = re.search(r"slurmstepd-node\d+: error: Detected (\d+) oom-kill event", line)
                    if m:
                        ooms.append(m.group(1))
                        break

    runs.append(
        {
            "grid": grid.name,
            "nexp": nexp,
            "success": len(success),
            "failed": len(failed),
            "ooms": len(ooms),
            "success_rate": len(success) / nexp if nexp > 0 else None,
        }
    )

print(f"Number of grids: {ngrids}")
print(f"Number of experiments: {sum([r['nexp'] for r in runs])}")
print(f"Number of successful experiments: {sum([r['success'] for r in runs])}")
print(f"Number of failed experiments: {sum([r['failed'] for r in runs])}")
print(f"Number of OOMs: {sum([r['ooms'] for r in runs])}")
print(f"Success rate: {sum([r['success'] for r in runs]) / sum([r['nexp'] for r in runs])}")

pd.DataFrame(runs)

100%|██████████| 33/33 [00:10<00:00,  3.05it/s]

Number of grids: 0
Number of experiments: 1320
Number of successful experiments: 1213
Number of failed experiments: 107
Number of OOMs: 97
Success rate: 0.918939393939394

                grid  nexp  success  failed  ooms  success_rate
0   gridsearch_00000    40       40       0     0         1.000
1   gridsearch_00001    40       40       0     0         1.000
2   gridsearch_00002    40       25      15     5         0.625
3   gridsearch_00003    40       40       0     0         1.000
4   gridsearch_00004    40       40       0     0         1.000
5   gridsearch_00005    40       40       0     0         1.000
6   gridsearch_00006    40       38       2     2         0.950
7   gridsearch_00007    40       38       2     2         0.950
8   gridsearch_00008    40       35       5     5         0.875
9   gridsearch_00009    40       38       2     2         0.950
10  gridsearch_00010    40       38       2     2         0.950
11  gridsearch_00011    40       40       0     0         1.000
12  gridsearch_00012    40       20      20    20         0.500
13  gridsearch_00013    40       40       0     0         1.000
14  gridsearch_00014    40        0      40    40         0.000
15  gridsearch_00015    40       39       1     1         0.975
16  gridsearch_00016    40       39       1     1         0.975
17  gridsearch_00017    40       37       3     3         0.925
18  gridsearch_00018    40       38       2     2         0.950
19  gridsearch_00019    40       33       7     7         0.825
20  gridsearch_00020    40       40       0     0         1.000
21  gridsearch_00021    40       40       0     0         1.000
22  gridsearch_00022    40       40       0     0         1.000
23  gridsearch_00023    40       38       2     2         0.950
24  gridsearch_00024    40       40       0     0         1.000
25  gridsearch_00025    40       39       1     1         0.975
26  gridsearch_00026    40       40       0     0         1.000
27  gridsearch_00027    40       39       1     1         0.975
28  gridsearch_00028    40       40       0     0         1.000
29  gridsearch_00029    40       40       0     0         1.000
30  gridsearch_00030    40       39       1     1         0.975
31  gridsearch_00031    40       40       0     0         1.000
32  gridsearch_00032    40       40       0     0         1.000

In [79]:
def _load_tomtom(f) -> float:
    result = pd.read_csv(f, sep="\t", comment="#", header=0)
    if len(result) == 0:
        print(f"[WARNING] >>> Empty tomtom result file {f}, returning -1 as ppval!")
        return -1
    
    pval = result["p-value"].min()
    # negative log10 of p-value
    ppval = -math.log10(pval)
    return ppval

In [80]:
results = {
    "grid": [],
    "experiments": [],
    "runtimes": [],
    "ppvals": [],
}
for grid in tqdm(sorted(list(wd.glob("gridsearch_*/")))):
    experiments = list(grid.glob("wgEncode*/"))
    results["grid"].append(grid.name)
    valid_experiments = []
    runtimes = []
    ppvals = []
    # print(f"Experiments: {experiments}")
    for exp in experiments:
        # print(f"Processing {exp.name}")
        if (exp / "tomtom" / "tomtom.tsv").exists():
            slurmerrf: Path = slurmoutToExp[grid.name][exp.name]
            slourmoutf = slurmerrf.with_suffix(".out")
            runtime = None
            with open(slourmoutf, "r") as f:
                for line in f:
                    m = re.search("Job "+grid.name+r" finished in (\d+) seconds", line)
                    if m:
                        runtime = int(m.group(1))
                        break

            assert runtime is not None, f"Could not find runtime in {slourmoutf}"
            runtimes.append(runtime)
            valid_experiments.append(exp.name)
            tomtomf = exp / "tomtom" / "tomtom.tsv"
            ppval = _load_tomtom(tomtomf)
            ppvals.append(ppval)
        # else:
        #     print(f"Warning: {grid.name} has no tomtom result for {exp.name}")

    results["experiments"].append(valid_experiments)
    results["runtimes"].append(runtimes)
    results["ppvals"].append(ppvals)

  0%|          | 0/33 [00:00<?, ?it/s]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00000/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00000/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00000/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

  3%|▎         | 1/33 [00:03<01:58,  3.69s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00001/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

  6%|▌         | 2/33 [00:06<01:46,  3.43s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00002/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

  9%|▉         | 3/33 [00:08<01:23,  2.77s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00003/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00003/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00003/wgEncodeAwgTfbsSydhK562Rfx5IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00003/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 12%|█▏        | 4/33 [00:12<01:25,  2.96s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00004/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 15%|█▌        | 5/33 [00:15<01:26,  3.10s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00005/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00005/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00005/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 18%|█▊        | 6/33 [00:18<01:25,  3.16s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00006/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00006/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00006/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00006/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 21%|██        | 7/33 [00:22<01:23,  3.21s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00007/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00007/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00007/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 24%|██▍       | 8/33 [00:25<01:21,  3.24s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 27%|██▋       | 9/33 [00:28<01:15,  3.16s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00008/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00009/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00009/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00009/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00009/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00009/wgEncodeAwgTfbsSydhK562E2f6UcdUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 30%|███       | 10/33 [00:31<01:11,  3.11s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00010/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00010/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 33%|███▎      | 11/33 [00:34<01:08,  3.13s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00011/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00011/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00011/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 36%|███▋      | 12/33 [00:37<01:05,  3.14s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00012/wgEncodeAwgTfbsHaibK562Ets1V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00012/wgEncodeAwgTfbsHaibK562Sp1Pcr1xUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00012/wgEncodeAwgTfbsSydhK562Irf1Ifng30UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00012/wgEncodeAwgTfbsSydhK562E2f4UcdUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 39%|███▉      | 13/33 [00:39<00:53,  2.67s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00012/wgEncodeAwgTfbsSydhK562Nrf1IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00013/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00013/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 48%|████▊     | 16/33 [00:45<00:39,  2.32s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00016/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00016/wgEncodeAwgTfbsSydhK562Atf3UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00016/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00016/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 52%|█████▏    | 17/33 [00:49<00:43,  2.70s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00017/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00017/wgEncodeAwgTfbsHaibK562Egr1V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00017/wgEncodeAwgTfbsHaibK562E2f6V0416102UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00017/wgEncodeAwgTfbsSydhK562Irf1Ifna6hUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00017/wgEncodeAwgTfbsSydhK562Irf1Ifng30UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00017/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00017/wgEncodeAwgTfbsSydhK562E2f4UcdUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00017/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 55%|█████▍    | 18/33 [00:51<00:39,  2.66s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00017/wgEncodeAwgTfbsSydhK562E2f6UcdUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00018/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00018/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00018/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 58%|█████▊    | 19/33 [00:54<00:38,  2.73s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00019/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00019/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 61%|██████    | 20/33 [00:57<00:37,  2.87s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00020/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00020/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00020/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 64%|██████▎   | 21/33 [01:01<00:37,  3.09s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00021/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00021/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00021/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 67%|██████▋   | 22/33 [01:04<00:34,  3.12s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00022/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00022/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00022/wgEncodeAwgTfbsSydhK562Rfx5IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00022/wgEncodeAwgTfbsSydhK562MaxIggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 70%|██████▉   | 23/33 [01:07<00:30,  3.09s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00023/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00023/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00023/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 73%|███████▎  | 24/33 [01:10<00:28,  3.11s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00024/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00024/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00024/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00024/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 76%|███████▌  | 25/33 [01:14<00:26,  3.28s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00025/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00025/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 79%|███████▉  | 26/33 [01:17<00:22,  3.21s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00026/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00026/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00026/wgEncodeAwgTfbsSydhK562Rfx5IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 82%|████████▏ | 27/33 [01:20<00:19,  3.19s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00027/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00027/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00027/wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 85%|████████▍ | 28/33 [01:23<00:15,  3.11s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00028/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00028/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00028/wgEncodeAwgTfbsSydhK562MaxIggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00028/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 88%|████████▊ | 29/33 [01:26<00:12,  3.08s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00029/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00029/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 91%|█████████ | 30/33 [01:28<00:08,  2.80s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00030/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00030/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 94%|█████████▍| 31/33 [01:30<00:04,  2.44s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00030/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00031/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00031/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

 97%|█████████▋| 32/33 [01:31<00:02,  2.14s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00031/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00032/wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!
[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00032/wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

100%|██████████| 33/33 [01:33<00:00,  2.83s/it]

[WARNING] >>> Empty tomtom result file .brain_mnt/runs/20250428_gridsearch_STREME_vs_ProfileFinding/gridsearch_00032/wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak/tomtom/tomtom.tsv, returning -1 as ppval!

In [81]:
results["experiments"][0]

['wgEncodeAwgTfbsHaibK562SrfV0416101UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Gata2UcdUniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Tead4sc101184V0422111UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562MaffIggrabUniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Egr1V0416101UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Elk112771IggrabUniPk.narrowPeak',
 'wgEncodeAwgTfbsUtaK562CtcfUniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Atf3V0416101UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Usf2IggrabUniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Ets1V0416101UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Bhlhe40nb100IggrabUniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Nfe2UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Gata1UcdUniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Gata2sc267Pcr1xUniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Atf3UniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Elf1sc631V0416102UniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Usf1V0416101UniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562E2f6V0416102UniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Yy1V0416101UniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562MaxV0416102UniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Yy1V0416102UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Irf1Ifna30UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Rfx5IggrabUniPk.narrowPeak',
 'wgEncodeAwgTfbsBroadK562CtcfUniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Mef2aV0416101UniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Sp1Pcr1xUniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Irf1Ifna6hUniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Nr2f2sc271940V0422111UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562CebpbIggrabUniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Irf1Ifng30UniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Zbtb7asc34508V0416101UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Yy1UcdUniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Atf106325UniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562E2f4UcdUniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562MaxIggrabUniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Znf143IggrabUniPk.narrowPeak',
 'wgEncodeAwgTfbsUwK562CtcfUniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562Nrf1IggrabUniPk.narrowPeak',
 'wgEncodeAwgTfbsSydhK562E2f6UcdUniPk.narrowPeak',
 'wgEncodeAwgTfbsHaibK562Sp2sc643V0416102UniPk.narrowPeak']

In [82]:
flat_dict = {
    "grid": [],
    "experiment": [],
    "runtime": [],
    "ppval": [],
}
sum_dict = {
    "grid": [],
    "mean runtime": [],
    "std runtime": [],
    "mean ppval": [],
    "std ppval": [],
}
for i, grid in enumerate(results["grid"]):
    assert len(results["experiments"][i]) == len(results["runtimes"][i])
    assert len(results["experiments"][i]) == len(results["ppvals"][i])
    if len(results["experiments"][i]) == 0:
        print(f"Warning: {grid} has no valid experiments")
        continue
    
    for exp, runtime, ppval in zip(results["experiments"][i], results["runtimes"][i], results["ppvals"][i]):
        flat_dict["grid"].append(grid)
        flat_dict["experiment"].append(exp)
        flat_dict["runtime"].append(runtime)
        flat_dict["ppval"].append(ppval)

    sum_dict["grid"].append(grid)
    sum_dict["mean runtime"].append(statistics.mean(results["runtimes"][i]))
    sum_dict["std runtime"].append(statistics.stdev(results["runtimes"][i]))
    sum_dict["mean ppval"].append(statistics.mean(results["ppvals"][i]))
    sum_dict["std ppval"].append(statistics.stdev(results["ppvals"][i]))

df_flat = pd.DataFrame(flat_dict)
df_sum = pd.DataFrame(sum_dict)

Warning: gridsearch_00014 has no valid experiments

In [83]:
df_sum.sort_values("mean ppval", ascending=False, inplace=True)
df_sum.reset_index(drop=True, inplace=True)
df_sum

                grid  mean runtime  std runtime  mean ppval  std ppval
0   gridsearch_00015   4129.128205  3260.859898    4.886516   2.398714
1   gridsearch_00007   4064.447368  3586.196326    4.666014   2.959800
2   gridsearch_00008   3926.228571  3600.519310    4.214837   2.166985
3   gridsearch_00002   3617.320000  2292.063730    4.086987   2.164988
4   gridsearch_00021   3964.425000  3193.387671    3.927315   2.145406
5   gridsearch_00020   4295.125000  3449.242021    3.923696   2.157344
6   gridsearch_00025   4657.179487  4340.813705    3.913898   2.193587
7   gridsearch_00026   4925.650000  4388.800120    3.907626   2.272405
8   gridsearch_00005   4768.550000  4127.401858    3.894501   2.347384
9   gridsearch_00027   4238.128205  3730.763660    3.886345   2.292470
10  gridsearch_00000   4792.400000  4031.454505    3.852606   2.167418
11  gridsearch_00031   4770.250000  4024.041200    3.852606   2.167418
12  gridsearch_00032   4759.600000  4003.700422    3.852606   2.167418
13  gridsearch_00022   2797.375000  2638.905889    3.831456   2.337352
14  gridsearch_00013   4790.775000  4333.769766    3.831225   2.032429
15  gridsearch_00029   3700.000000  3421.131010    3.828615   2.195960
16  gridsearch_00023   4058.236842  3513.303762    3.797381   2.299088
17  gridsearch_00004   4741.275000  4060.250984    3.779584   2.223392
18  gridsearch_00003   4745.700000  4009.973829    3.776155   2.331067
19  gridsearch_00011   4754.550000  4278.585382    3.772234   2.078937
20  gridsearch_00030   5206.794872  4409.333839    3.763704   2.193527
21  gridsearch_00001   3212.150000  3203.221564    3.734047   2.108437
22  gridsearch_00018   4843.578947  4119.415529    3.685571   2.274084
23  gridsearch_00028   4199.125000  3933.483777    3.665244   2.330211
24  gridsearch_00019   4255.242424  3507.906944    3.598621   2.111599
25  gridsearch_00010   4251.078947  3627.950575    3.501455   1.667912
26  gridsearch_00006   4300.631579  3778.821827    3.482036   2.268724
27  gridsearch_00024   4692.375000  4027.562275    3.469953   2.178844
28  gridsearch_00009   5353.473684  4080.860122    3.053310   2.119038
29  gridsearch_00012   2811.800000  2189.235017    3.011724   3.089434
30  gridsearch_00016   5013.871795  4378.602734    2.598253   1.704165
31  gridsearch_00017   5089.432432  4539.878679    1.314347   1.445812

In [84]:
plotting.boxplotNumColumn(df_flat, column="ppval", byColumn="grid", title="Motif Similarity Score", label="Grid", ylab="-log10(p-value)")

In [86]:
plotting.boxplotNumColumn(df_flat, column="runtime", byColumn="grid", title="Runtime", label="Grid", ylab="runtime (s)")

gridsearch_00015 should be the new baseline for further grid searches. This means mellowmax_alpha = 0.5 works best for 
the current set of parameters.

In [87]:
def get_config(grid: Path) -> dict:
    experiments = list(grid.glob("wgEncode*/"))
    config = None
    for exp in experiments:
        configf = exp / "settings.json"
        assert configf.exists(), f"Config file {configf} does not exist"
        with open(configf, "r") as f:
            _config: dict = json.load(f)
        _config.pop("fasta")
        _config.pop("out")
        if config is not None:
            assert _config == config, f"Config files {configf} and {config} are different"
        else:
            config = _config

    return config

In [88]:
grid_configs = {
    grid.name: get_config(grid) for grid in tqdm(sorted(list(wd.glob("gridsearch_*/"))))
}

  0%|          | 0/33 [00:00<?, ?it/s]

100%|██████████| 33/33 [00:40<00:00,  1.23s/it]

In [90]:
grid_diffs = {
    g: {
        k: v
        for k, v in grid_configs[g].items()
        if grid_configs["gridsearch_00000"][k] != grid_configs[g][k]
    } for g in grid_configs
}
grid_diffs

{'gridsearch_00000': {},
 'gridsearch_00001': {'U': 50},
 'gridsearch_00002': {'U': 500},
 'gridsearch_00003': {'overlapTilesize': 1},
 'gridsearch_00004': {'overlapTilesize': 10},
 'gridsearch_00005': {'midK': 8},
 'gridsearch_00006': {'midK': 10},
 'gridsearch_00007': {'gamma': 0.5},
 'gridsearch_00008': {'gamma': 0.01},
 'gridsearch_00009': {'gamma': 2.0},
 'gridsearch_00010': {'kld': 0.1},
 'gridsearch_00011': {'kld': 0.001},
 'gridsearch_00012': {'kld': 1.0},
 'gridsearch_00013': {'kld': 0.0},
 'gridsearch_00014': {'mellowmax_alpha': 0.0},
 'gridsearch_00015': {'mellowmax_alpha': 0.5},
 'gridsearch_00016': {'mellowmax_alpha': 2.0},
 'gridsearch_00017': {'mellowmax_alpha': 5.0},
 'gridsearch_00018': {'match_score_factor': 0.6},
 'gridsearch_00019': {'match_score_factor': 0.5},
 'gridsearch_00020': {'match_score_factor': 0.8},
 'gridsearch_00021': {'match_score_factor': 0.9},
 'gridsearch_00022': {'learning_rate': 0.1},
 'gridsearch_00023': {'learning_rate': 1.0},
 'gridsearch_00024': {'learning_rate': 4.0},
 'gridsearch_00025': {'lr_patience': 10},
 'gridsearch_00026': {'lr_patience': 15},
 'gridsearch_00027': {'lr_factor': 0.5},
 'gridsearch_00028': {'lr_factor': 0.25},
 'gridsearch_00029': {'profile_plateau': 5},
 'gridsearch_00030': {'profile_plateau': 15},
 'gridsearch_00031': {'profile_plateau_dev': 100.0},
 'gridsearch_00032': {'profile_plateau_dev': 200.0}}

In [91]:
config_df_dict = {
    'parameter': [],
    'grid': [],
    'value': [],
    'mean ppval': [],
    'std ppval': [],
    'delta ppval': [],
    'mean runtime': [],
    'std runtime': [],
    'delta runtime': [],
}
base_ppval = df_sum[df_sum["grid"] == "gridsearch_00000"]["mean ppval"].values[0]
base_ppval_std = df_sum[df_sum["grid"] == "gridsearch_00000"]["std ppval"].values[0]
base_runtime = df_sum[df_sum["grid"] == "gridsearch_00000"]["mean runtime"].values[0]
base_runtime_std = df_sum[df_sum["grid"] == "gridsearch_00000"]["std runtime"].values[0]
current_param = None
for grid, config in grid_diffs.items():
    if len(config) == 0:
        continue
    if grid not in df_sum["grid"].values:
        print(f"Warning: {grid} not in df_sum")
        continue
    assert len(config) == 1, f"Grid {grid} has more than one config parameter"
    param = list(config.keys())[0]
    value = config[param]
    mean_ppval = df_sum[df_sum["grid"] == grid]["mean ppval"].values[0]
    std_ppval = df_sum[df_sum["grid"] == grid]["std ppval"].values[0]
    mean_runtime = df_sum[df_sum["grid"] == grid]["mean runtime"].values[0]
    std_runtime = df_sum[df_sum["grid"] == grid]["std runtime"].values[0]
    if current_param is None or current_param != param:
        config_df_dict["parameter"].append(param)
        config_df_dict["grid"].append("gridsearch_00000")
        config_df_dict["value"].append(grid_configs["gridsearch_00000"][param])
        config_df_dict["mean ppval"].append(base_ppval)
        config_df_dict["std ppval"].append(base_ppval_std)
        config_df_dict["delta ppval"].append(0)
        config_df_dict["mean runtime"].append(base_runtime)
        config_df_dict["std runtime"].append(base_runtime_std)
        config_df_dict["delta runtime"].append(0)
        current_param = param

    config_df_dict["parameter"].append(param)
    config_df_dict["grid"].append(grid)
    config_df_dict["value"].append(value)
    config_df_dict["mean ppval"].append(mean_ppval)
    config_df_dict["std ppval"].append(std_ppval)
    config_df_dict["delta ppval"].append(mean_ppval - base_ppval)
    config_df_dict["mean runtime"].append(mean_runtime)
    config_df_dict["std runtime"].append(std_runtime)
    config_df_dict["delta runtime"].append(mean_runtime - base_runtime)

config_df = pd.DataFrame(config_df_dict)
print(df_sum[df_sum['grid'] == 'gridsearch_00000'])
config_df

Warning: gridsearch_00014 not in df_sum
                grid  mean runtime  std runtime  mean ppval  std ppval
10  gridsearch_00000        4792.4  4031.454505    3.852606   2.167418

,parameter,grid,value,mean ppval,std ppval,delta ppval,mean runtime,std runtime,delta runtime
0,U,gridsearch_00000,200.000,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
1,U,gridsearch_00001,50.000,3.734047,2.108437,-0.118559,3212.150000,3203.221564,-1580.250000
2,U,gridsearch_00002,500.000,4.086987,2.164988,0.234381,3617.320000,2292.063730,-1175.080000
3,overlapTilesize,gridsearch_00000,6.000,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
4,overlapTilesize,gridsearch_00003,1.000,3.776155,2.331067,-0.076451,4745.700000,4009.973829,-46.700000
5,overlapTilesize,gridsearch_00004,10.000,3.779584,2.223392,-0.073022,4741.275000,4060.250984,-51.125000
6,midK,gridsearch_00000,6.000,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
7,midK,gridsearch_00005,8.000,3.894501,2.347384,0.041895,4768.550000,4127.401858,-23.850000
8,midK,gridsearch_00006,10.000,3.482036,2.268724,-0.370570,4300.631579,3778.821827,-491.768421
9,gamma,gridsearch_00000,1.000,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
10,gamma,gridsearch_00007,0.500,4.666014,2.959800,0.813408,4064.447368,3586.196326,-727.952632
11,gamma,gridsearch_00008,0.010,4.214837,2.166985,0.362231,3926.228571,3600.519310,-866.171429
12,gamma,gridsearch_00009,2.000,3.053310,2.119038,-0.799296,5353.473684,4080.860122,561.073684
13,kld,gridsearch_00000,0.010,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
14,kld,gridsearch_00010,0.100,3.501455,1.667912,-0.351151,4251.078947,3627.950575,-541.321053
15,kld,gridsearch_00011,0.001,3.772234,2.078937,-0.080372,4754.550000,4278.585382,-37.850000
16,kld,gridsearch_00012,1.000,3.011724,3.089434,-0.840882,2811.800000,2189.235017,-1980.600000
17,kld,gridsearch_00013,0.000,3.831225,2.032429,-0.021381,4790.775000,4333.769766,-1.625000
18,mellowmax_alpha,gridsearch_00000,1.000,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
19,mellowmax_alpha,gridsearch_00015,0.500,4.886516,2.398714,1.033910,4129.128205,3260.859898,-663.271795
20,mellowmax_alpha,gridsearch_00016,2.000,2.598253,1.704165,-1.254353,5013.871795,4378.602734,221.471795
21,mellowmax_alpha,gridsearch_00017,5.000,1.314347,1.445812,-2.538259,5089.432432,4539.878679,297.032432
22,match_score_factor,gridsearch_00000,0.700,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
23,match_score_factor,gridsearch_00018,0.600,3.685571,2.274084,-0.167036,4843.578947,4119.415529,51.178947
24,match_score_factor,gridsearch_00019,0.500,3.598621,2.111599,-0.253985,4255.242424,3507.906944,-537.157576
25,match_score_factor,gridsearch_00020,0.800,3.923696,2.157344,0.071090,4295.125000,3449.242021,-497.275000
26,match_score_factor,gridsearch_00021,0.900,3.927315,2.145406,0.074709,3964.425000,3193.387671,-827.975000
27,learning_rate,gridsearch_00000,2.000,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
28,learning_rate,gridsearch_00022,0.100,3.831456,2.337352,-0.021150,2797.375000,2638.905889,-1995.025000
29,learning_rate,gridsearch_00023,1.000,3.797381,2.299088,-0.055225,4058.236842,3513.303762,-734.163158
30,learning_rate,gridsearch_00024,4.000,3.469953,2.178844,-0.382653,4692.375000,4027.562275,-100.025000
31,lr_patience,gridsearch_00000,5.000,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
32,lr_patience,gridsearch_00025,10.000,3.913898,2.193587,0.061292,4657.179487,4340.813705,-135.220513
33,lr_patience,gridsearch_00026,15.000,3.907626,2.272405,0.055020,4925.650000,4388.800120,133.250000
34,lr_factor,gridsearch_00000,0.750,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
35,lr_factor,gridsearch_00027,0.500,3.886345,2.292470,0.033739,4238.128205,3730.763660,-554.271795
36,lr_factor,gridsearch_00028,0.250,3.665244,2.330211,-0.187362,4199.125000,3933.483777,-593.275000
37,profile_plateau,gridsearch_00000,10.000,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
38,profile_plateau,gridsearch_00029,5.000,3.828615,2.195960,-0.023991,3700.000000,3421.131010,-1092.400000
39,profile_plateau,gridsearch_00030,15.000,3.763704,2.193527,-0.088902,5206.794872,4409.333839,414.394872
40,profile_plateau_dev,gridsearch_00000,150.000,3.852606,2.167418,0.000000,4792.400000,4031.454505,0.000000
41,profile_plateau_dev,gridsearch_00031,100.000,3.852606,2.167418,0.000000,4770.250000,4024.041200,-22.150000
42,profile_plateau_dev,gridsearch_00032,200.000,3.852606,2.167418,0.000000,4759.600000,4003.700422,-32.800000

In [75]:
pseudo_optimal_config = {
    'U': 200,
    'overlapTilesize': 1,
    'midK': 6,
    'gamma': 0.01,
    'kld': 0.1,
    'mellowmax_alpha': 0.5,
    'match_score_factor': 0.8,
    'learning_rate': 1.0,
    'lr_patience': 15,
    'lr_factor': 0.25,
    'profile_plateau': 5,
    'profile_plateau_dev': 100,
}

for k, v in grid_configs['gridsearch_00000'].items():
    if k not in pseudo_optimal_config:
        pseudo_optimal_config[k] = v

print(pseudo_optimal_config)

with open(wd / "pseudo_optimal_config.json", "w") as f:
    json.dump(pseudo_optimal_config, f, indent=4)

{'U': 200, 'overlapTilesize': 1, 'midK': 6, 'gamma': 0.01, 'kld': 0.1, 'mellowmax_alpha': 0.5, 'match_score_factor': 0.8, 'learning_rate': 1.0, 'lr_patience': 15, 'lr_factor': 0.25, 'profile_plateau': 5, 'profile_plateau_dev': 100, 'mode': 'DNA', 'config': None, 'maxseqs': None, 'no_softmasking': False, 'do_not_train': False, 'rand_seed': 42, 'tile_size': 100, 'tiles_per_X': 1, 'batch_size': 1, 'prefetch': 3, 'n_best_profiles': 5, 'enforceU': False, 'minU': 10, 'minOcc': 8, 'k': 12, 's': 0, 'l2': 0.0, 'rho': 0.0, 'sigma': 1.0, 'phylo_t': 0.0}